# Generated by Django 3.0 on 2020-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlees', models.CharField(max_length=200, verbose_name='titulo')),
                ('subtitlees', models.CharField(max_length=200, verbose_name='subtitulo')),
                ('contentes', models.TextField(verbose_name='contenido')),
                ('imagees', models.ImageField(upload_to='services', verbose_name='imagen')),
                ('createdes', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updatedes', models.DateTimeField(auto_now=True, verbose_name='fecha de edicion ')),
            ],
        ),
    ]
